// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace WebUI.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class 添加SignalR相关 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(添加SignalR相关));
        
        string IMigrationMetadata.Id
        {
            get { return "201607071411044_添加SignalR相关"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
