// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace WebUI.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Unique添加索引 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Unique添加索引));
        
        string IMigrationMetadata.Id
        {
            get { return "201607061544246_Unique添加索引"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
