// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace WebUI.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class 修改中间表 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(修改中间表));
        
        string IMigrationMetadata.Id
        {
            get { return "201607211222261_修改中间表"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
