// <auto-generated />
namespace MVC_Learn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class 修改主键类型为long : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(修改主键类型为long));
        
        string IMigrationMetadata.Id
        {
            get { return "201607191453004_修改主键类型为long"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
