// <auto-generated />
namespace MVC_Learn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class 标题和作者不为空 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(标题和作者不为空));
        
        string IMigrationMetadata.Id
        {
            get { return "201607061549078_标题和作者不为空"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
