// <auto-generated />
namespace MVC_Learn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class 修改时间 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(修改时间));
        
        string IMigrationMetadata.Id
        {
            get { return "201607051629057_修改时间"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
