// <auto-generated />
namespace MVCLearn.ModelDbContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class 用户角色中间表 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(用户角色中间表));
        
        string IMigrationMetadata.Id
        {
            get { return "201612130822444_用户角色中间表"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
