// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-alpha1")]
    public sealed partial class HierarchyId自增 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HierarchyId自增));
        
        string IMigrationMetadata.Id
        {
            get { return "201608210910560_HierarchyId自增"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
