// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-alpha1")]
    public sealed partial class 添加部门表 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(添加部门表));
        
        string IMigrationMetadata.Id
        {
            get { return "201608210902247_添加部门表"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
